version: "3.9"

services:
  app:
    build: .
    container_name: minha-aplicacao
    ports:
      - "8080:8080"
    environment:
      DB_HOST: oracle-db
      DB_PORT: 1521
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: XE
    depends_on:
      - oracle-db
    networks:
      - minha-rede

  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-db
    environment:
      ORACLE_PASSWORD: admin123
      APP_USER: admin
      APP_USER_PASSWORD: admin123
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - minha-rede

volumes:
  oracle_data:

networks:
  minha-rede:
    driver: bridge
