name: CICDpipeline

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build com Maven
        run: mvn clean compile

  test:
    name: Testes
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Executar testes Maven
        run: mvn test

  deploy-staging:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Deploy para Staging
        run: |
          echo "Fazendo deploy no ambiente de staging..."
          # Substitua pelo comando real de deploy
          # Exemplo: scp target/meu-app.jar user@staging-server:/var/www/app

  deploy-prod:
    name: Deploy Produção
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy para Produção
        run: |
          echo "Fazendo deploy no ambiente de produção..."
          # Substitua pelo comando real de deploy
          # Exemplo: scp target/meu-app.jar user@prod-server:/var/www/app